/**
 * This file was generated by gen-env-types.
 * Please do not edit it manually.
 */

declare module "process" {
  global {
    namespace NodeJS {
      interface ProcessEnv {
        NODE_ENV?: string;
        DATABASE_URL?: string;
        JWT_SECRET?: string;
      }
    }
  }
}
