import fs from "node:fs";

const header = `/**
 * This file was generated by gen-env-types.
 * Please do not edit it manually.
 */

declare module "process" {
  global {
    namespace NodeJS {
      interface ProcessEnv {
`;

const footer = `
      }
    }
  }
}
`;

function main() {
  const envExample = fs.readFileSync(".env.example", "utf8");
  const body = envExample
    .split("\n")
    .map((x) => x.split("="))
    .map((x) => x.at(0)?.trim())
    .filter((x): x is string => typeof x == "string" && x.length > 0)
    .map((x) => `        ${x}?: string;`)
    .join("\n");
  const envDts = `${header}${body}${footer}`;
  fs.writeFileSync("types/env.d.ts", envDts);
}

main();
